### ISSUE TITLE
pg コマンドの作成

### ISSUE THREAD

**Issue by ryotayamanaka** [g2glab/pg#15]
現状は

    $ pg2pgx <pg_file> <output_prefix>

だが、

    $ pg convert -f pgx <pg_file>
    $ pg convert -f pgx -o <output_prefix> <pg_file>

とする？

**Comment by ryotayamanaka** [comment]
pgraph CLI will cover this UX:
https://github.com/gbv/pgraph?tab=readme-ov-file#cli

@hchiba1 @nichtich

**Comment by hchiba1** [comment]
Yeah, great work!!
Maybe we can close this issue.
