### ISSUE TITLE
データ型についてまとめる

### ISSUE THREAD

**Issue by ryotayamanaka** [g2glab/pg#2]
PG 形式は可視性を重視した形式なのでデータ型を宣言していない。そのため、他の形式に変換するときにデータ型を自動判別しているので、このルールについて仕様としてまとめておきたい。

今のところは以下のようなルール（pg_to.evalType）：

* 文字列、または "" で囲まれている => string
* 数値、ピリオドが含まれない => integer
* 数値、ピリオドが含まれる => double

追加したいのは：

* boolean と datetime はどうする？
* float は無視してしまう？

**Comment by ryotayamanaka** [comment]
https://pg-format.readthedocs.io/en/0.3/contents/pg-format.html#data-type

**Comment by ryotayamanaka** [comment]
**boolean** and **datetime** are stored as **string**. Is this ok? @matsusho070

**Comment by hchiba1** [comment]
followed by the discussion:
https://github.com/orgs/pg-format/discussions/14
