### ISSUE TITLE
pg2pgx uses underscore in property

### ISSUE THREAD

**Issue by shota-matsumoto-lm** [g2glab/pg#23]
Current PGQL does not allow underscore as property name ([ref.](https://docs.oracle.com/cd/E56133_01/latest/reference/analytics/pgql.html#property-names)), while pg2pgx uses '_label' property.

**Comment by ryotayamanaka** [comment]
It seems the current PGX allows `_`.

**Comment by ryotayamanaka** [comment]
pg2pgx will be replaced to pg2csv, so `_label` does not needed.

However, we still need to check if PGQL allows underscore in property name.

**Comment by ryotayamanaka** [comment]
This queyr is allowed in the PGQL syntax and works (tested on Graph Studio)
```
insert into test1 vertex v labels ("_label") properties (v."_prop" = 1);
```

**Comment by ryotayamanaka** [comment]
We don't need to maintain pg2pgx anymore, anyway.
