### ISSUE TITLE
GPG の soundness を確認するプログラムの作成

### ISSUE THREAD

**Issue by ryotayamanaka** [g2glab/pg#4]
生成された GPG が (1) 文法的に (2) 意味的に 正しいかどうかを確認する。ここで、意味的に正しくない、というのがどういう場合か（例えば、Node ID の重複は OK？）といった点は別途それぞれ考慮し、それらを反映させる。

**Comment by hchiba1** [comment]
followed by the discussion:
https://github.com/orgs/pg-format/discussions/16
