### ISSUE TITLE
他のフォーマットとの違いを記述する

### ISSUE THREAD

**Issue by ryotayamanaka** [g2glab/pg#9]
GML / GraphML / GraphSON との違いは？
特に、JSON-PG と GraphSON は非常に近いので、なぜ PG でないといけないか明確にする

**Comment by ryotayamanaka** [comment]
should be described here:
https://pg-format.readthedocs.io/en/0.3/contents/pg-format.html#comparing-the-formats

**Comment by hchiba1** [comment]
Followed by:
* https://github.com/orgs/pg-format/discussions/40
